=== kbbansi/tlc-data-week/dtds/libraryex.dtd
<!ELEMENT library (bookTitle, author, callNumber, stock, aisle)>
<!ELEMENT bookTitle (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT callNumber (subject, authorLastName , publicationDate)>
<!ELEMENT stock (#PCDATA)>
<!ELEMENT aisle (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT authorLastName (#PCDATA)>
<!ELEMENT publicationDate (#PCDATA)>

=== kbbansi/tlc-data-week/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "libraryex.dtd">

<library>
    <bookTitle>Harry Potter and The Sorceror's Stone</bookTitle>
    <author>J.K Rowling</author>
    <callNumber>
        <subject>Fiction</subject>
        <authorLastName>Rowling</authorLastName>
        <publicationDate>1999</publicationDate>
    </callNumber>
    <stock>20</stock>
    <aisle>7B</aisle>
</library>
